### ISSUE TITLE
Unable to render DataGrid inside snippet using AJAX

### ISSUE THREAD

**Issue by MartinMystikJonas** [uestla/twigrid#13]
We have DataGrid control inside snippet. If we make AJAX request which invalidates this snippet DataGrid ens in fatal error. Reason is passForm() mechanism. Form is not passed to template and it fails to render.

If we remove passForm conditions from render method (currently line 871) eberything works as expected.

What is purpose of this condition?

**Comment by uestla** [comment]
You're right. I thought in some cases it isn't necessary to pass the form to the template so that it is as lazy as possible. But it's not that much of a overhead since the form itself by default does not contain nearly any elements (they are appended dynamically and lazy as well). So I removed the `passForm()` method and pass the $form variable every time.

Thanks a lot for your contributions!

**Comment by MartinMystikJonas** [comment]
Well, I thank for your grid ;-)
