### ISSUE TITLE
Localization of "No data." message

### ISSUE THREAD

**Issue by lupo112** [uestla/TwiGrid#22]
Hi!
Currently the message "no data" is showing directly in body block. If we want to change this message, there is need to rewrite the whole body block (around 60 lines of code) just to use something like `_'admin.grid.empty'`.

Can you split the body block into smaller pieces? Or at least define new block for the message? Something like

```
{define body-empty}
```

Or an option for defining empty message for the given grid? Something like

```
$grid->setEmptyMessage('admin.grid.empty');
```

Or do you have any other idea how to deal with this?

**Comment by uestla** [comment]
Hi, thank you for your question.

The same has been answered (with PR) [in January](https://github.com/uestla/TwiGrid/pull/16).

I know about this and am not happy about current block customization state either. I'm planning to increase block granularity so that it will be much easier to change table layout to custom rendering and empty data block will definitelly be part of it.

Maybe I'll just add the empty block sooner so it won't be that much of a pain in the current version.
