### ISSUE TITLE
Possibility to wrap header to multiple lines.

### ISSUE THREAD

**Issue by tprochazka** [uestla/TwiGrid#26]
Would be great if will be possible do this

`$this->addColumn('area', "Plocha bytu\n[m²]");`

Currently it is possible by customize template, but maybe something like this should be supported in the default one, just by adding `|breaklines`

**Comment by uestla** [comment]
I'm sorry, but it would be too unexpected for me to have this filter applied by default.

The thing is that most of the grids do not have multiline headers and the filter would therefore be called unnecessarily.

But [I just added](https://github.com/uestla/TwiGrid/commit/2156f017cde6089d80dbedf17a5b10d58eb36e0d) a new block `column-label` which you can extend in your template simply as

```
{define column-label}
	{$column->getLabel() |breaklines}
{/define}
```

so that you don't have to copy-paste all other HTML structure of the cell.

**Comment by tprochazka** [comment]
Great. I'm currently using

```
{define header-cell}

    <th n:class='header-cell, "header-cell-{$column->getName()}"'>
        <a href="{$sortLink}" n:class='sort, "sort-{$column->getName()}", tw-ajax' n:tag-if="$column->isSortable()">
            {$column->getLabel()|breaklines}
        </a>

        {include #sort-labels, (expand) get_defined_vars()}
    </th>

{/define}

```
So  column-label is much much better.

**Comment by uestla** [comment]
Glad to hear that :-)

Closing...
